[package]
name = "anytrio/anirio-table"
description = """A class to simplify and optimize table accessing, inserting, and removing;
Implements a set/multiset-like data structure for indexing values;
Part of Anirio Utility"""

version = "1.0.0"
license = "MIT"
authors = ["Mario Chao"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**/*/wally.toml"]

[dependencies]
