[package]
name = "anytrio/servers"
description = """A utility to simplify teleporting players between places and servers;
Automates various aspects of TeleportService and TeleportAsync;
Part of Anirio Utility"""

version = "0.1.0"
license = "MIT"
authors = ["Mario Chao"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**/*/wally.toml"]

[dependencies]
