[package]
name = "anytrio/player-utility"
description = """A utility to provide more features to the Players service;
Includes CharacterAdded and Removing signals/events for all players, which simplifies connections;
Part of Anirio Utility"""

version = "1.1.0"
license = "MIT"
authors = ["Mario Chao"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/AnyTrio/AnirioUtility"
exclude = ["**/*/wally.toml"]

[dependencies]
Character = "anytrio/character@1"
Signal = "sleitnick/signal@2"
