[package]
name = "anytrio/cframeutility"
description = """A utility to perform common and complex CFrame calculations;
Part of Anirio Utility"""

version = "1.0.0"
license = "MIT"
authors = ["Mario Chao"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = ["**/*/wally.toml"]

[dependencies]
