--!strict

-- Utility Module Template

-- Template by Panicks28


---------- Services ----------

---------- Imports ----------

local Packages = script.Parent


---------- Types ----------

---------- Constants ----------

---------- Globals ----------

---------- Local functions ----------

---------- Module ----------

local SomeModule = {}


----- Module fields -----

---------- Return module ----------

table.freeze(SomeModule)
return SomeModule
