--!strict
-- Utility Module Template

-- Template by Panicks28

---------- Module ----------
local SomeModule = {}

---------- Services ----------

---------- Imports ----------

---------- Types ----------

---------- Instances ----------

---------- Variables ----------

---------- Module variables ----------

---------- Local functions ----------

---------- Event functions ----------

---------- Module functions ----------

---------- Calling / connecting functions ----------

---------- Return module ----------
return SomeModule
